<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Khng ng (16)</name>
   <tag></tag>
   <elementGuidId>3ffa681a-7ec8-4873-a12c-add628157fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onesignal-slidedown-cancel-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onesignal-slidedown-cancel-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Không đồng ý&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eea3d298-8658-4170-af49-9730a70a00ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right secondary slidedown-button</value>
      <webElementGuid>978214a4-9abf-4885-8ceb-e0d8a87de352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onesignal-slidedown-cancel-button</value>
      <webElementGuid>96bf4b86-e200-4a3c-ad6b-dfa1c06db8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Không đồng ý</value>
      <webElementGuid>9dc45ad1-379b-4e32-b4f3-6b452328caca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onesignal-slidedown-cancel-button&quot;)</value>
      <webElementGuid>d90488c7-744e-4315-8e69-a04a65f0bfe3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onesignal-slidedown-cancel-button']</value>
      <webElementGuid>b0c24998-d03b-406e-9c61-370d022340c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button[2]</value>
      <webElementGuid>f84ea9e2-253f-4ca9-87a9-81e69d47df36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đồng Ý'])[1]/following::button[1]</value>
      <webElementGuid>a858cad2-62ca-4070-bbfd-f6d18ae98294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click vào Đồng Ý để nhận thông tin khuyến mãi nhanh nhất từ Hasaki'])[1]/following::button[2]</value>
      <webElementGuid>038f5497-488d-424d-892a-1f6f989e5d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Không đồng ý']/parent::*</value>
      <webElementGuid>4661dd2c-4cd6-40d0-a53f-d166b63dac60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>9cf4411d-79c7-4538-8ccb-68421f7fe20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onesignal-slidedown-cancel-button' and (text() = 'Không đồng ý' or . = 'Không đồng ý')]</value>
      <webElementGuid>7a4ffb1d-de9b-4d98-a469-bc75b1e5cebc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
