<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Xem tt c_img_thumb lazy loaded</name>
   <tag></tag>
   <elementGuidId>e8faecc1-3364-429f-b21f-1046efdc14c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img_thumb.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;18%&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb34e50b-b480-423f-b0e2-b722fb6f4e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_thumb lazy loaded</value>
      <webElementGuid>ce3b9408-ad18-441f-b0ec-a277ba4a4419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-son-duong-moi-khong-mau-dhc-ho-tro-giam-tham-moi-1-5g_XpUzhFzw2yKeYwH8_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>462aec27-6bbb-43ef-a905-15f707ba7fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>imgError(this);</value>
      <webElementGuid>00c4343e-ae95-47a4-ae6c-0b6a8050ac15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-son-duong-moi-khong-mau-dhc-ho-tro-giam-tham-moi-1-5g_XpUzhFzw2yKeYwH8_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>b11e0224-58e5-49b0-8ca5-dcf80a4035d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fb229655-26c8-4ebc-ba1c-c9a1c0a49237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ce18f8d2-63c5-4d4a-8453-c8d055b258dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giatot_daily&quot;)/div[@class=&quot;width_common&quot;]/div[@class=&quot;flexslider&quot;]/div[@class=&quot;flex-viewport&quot;]/ul[@class=&quot;slides&quot;]/li[1]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;img_thumb lazy loaded&quot;]</value>
      <webElementGuid>044a6f4e-ede0-4984-b7fd-03e8dca4b53d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li/div/a/img</value>
      <webElementGuid>88309669-e2a9-404f-8e83-6df810cf8fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-son-duong-moi-khong-mau-dhc-ho-tro-giam-tham-moi-1-5g_XpUzhFzw2yKeYwH8_img_220x220_0dff4c_fit_center.png')]</value>
      <webElementGuid>6c628020-b122-43d2-97ee-50c3410fea45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/a/img</value>
      <webElementGuid>30e3d8d5-0d9e-4798-ba36-244e14899ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-son-duong-moi-khong-mau-dhc-ho-tro-giam-tham-moi-1-5g_XpUzhFzw2yKeYwH8_img_220x220_0dff4c_fit_center.png']</value>
      <webElementGuid>c20300a3-415c-481c-96e6-71df5335fb84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
