<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_H trkhch hng_loading (3)</name>
   <tag></tag>
   <elementGuidId>bc6e5ce2-53f8-4215-ad8a-7785b1a2689b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icon_header.relative > div > img.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#v3_header >> internal:role=link[name=&quot;1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2e451cde-0fec-438c-a82e-60fbee6b3b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/icon_header__cart.png</value>
      <webElementGuid>e2aa81ac-6ed6-4fdf-a5bb-ddde7ca3aec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>ad9a8cb4-36ae-4b10-ac4a-6f0f096a2057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0a457919-a921-4945-8329-7690331bc218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v4_inf_right_header&quot;]/div[@class=&quot;item_header item_header_giohang minicart-wrapper&quot;]/a[@class=&quot;icon_header relative&quot;]/div[1]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>d751336a-4660-4730-a7c2-647483b87173</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      <webElementGuid>892a89a4-a2e7-4cf4-93a7-0ba78067d72a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/icon_header__cart.png')]</value>
      <webElementGuid>9c8d78cf-a2db-4b13-adbf-eb4900ebfa62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>1a5b2098-a60c-4f25-9169-9f928db5a8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/icon_header__cart.png']</value>
      <webElementGuid>3de2813d-d2f5-4b7e-b8f2-f085dfa8dfa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
