<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mua L C Qu_lazy loaded</name>
   <tag></tag>
   <elementGuidId>931b6a53-ac0d-4532-b919-d6722bd2736e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item_category_top.item_category_top_6 > a > span.icon_lam_category_top > img.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box_icon_category']/div/div/div[7]/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đặt Hẹn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a177efdb-b8ca-4d9c-bbcb-543d100037b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>imgError(this)</value>
      <webElementGuid>75c04a1b-9caa-4189-9431-9d5b1c11ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>32921afc-d34b-48be-9277-8037bfeb1ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png</value>
      <webElementGuid>e787f653-9f4b-4c7c-b0b8-610f631ad417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png</value>
      <webElementGuid>17ed97c6-ed05-4e2d-bebf-428460d880c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0489f839-9501-46c7-a78c-d82344089172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box_icon_category&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;list_category_top&quot;]/div[@class=&quot;item_category_top item_category_top_6&quot;]/a[1]/span[@class=&quot;icon_lam_category_top&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>a4380037-5dd1-47e1-880e-478cceb3d109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box_icon_category']/div/div/div[7]/a/span/img</value>
      <webElementGuid>9f3fc5cf-5977-4bb9-b605-ab1e2d1b5018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png')]</value>
      <webElementGuid>7dcf1c7c-cdc8-4dbe-804f-ee6aa94a1c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/span/img</value>
      <webElementGuid>9de3ac5f-e3b2-4401-8915-a6cf9d6e1c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png']</value>
      <webElementGuid>31487e97-4cf7-4d61-a2b4-d878a355481d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
