<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Retinol_icon_search loaded</name>
   <tag></tag>
   <elementGuidId>2746b762-c9ad-4cc7-bc97-6d7fdf6f6e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.icon_search.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form']/div[2]/div/div/div[2]/button/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>972b6854-16d4-4d75-9c39-1508af228453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/v3/images/icons/search_icon.svg</value>
      <webElementGuid>f6a73f66-cd8b-4c11-b6e1-268a9d052d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_search loaded</value>
      <webElementGuid>0dd01f02-803b-4bf8-8219-c5a605ad98fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>61ed5a5e-9233-4b90-94b5-1a0a6afba9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form&quot;)/div[@class=&quot;v3_block_search_header&quot;]/div[@class=&quot;relative width_common&quot;]/div[@class=&quot;v3_block_input_search width_common&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;btn_submit_search&quot;]/img[@class=&quot;icon_search loaded&quot;]</value>
      <webElementGuid>b360cdfb-b4d7-4cf8-9307-1cbbe9e82883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div[2]/div/div/div[2]/button/img</value>
      <webElementGuid>e5549872-ead0-4610-8fc1-79ad57fab630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/v3/images/icons/search_icon.svg')]</value>
      <webElementGuid>d4a0f202-fce6-41d6-a660-11b92c8a81d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>c0b8c291-06b8-4636-b2d4-6bec7e10e71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/v3/images/icons/search_icon.svg']</value>
      <webElementGuid>21882a73-b656-4e41-93cf-0ce0f5c1fa25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
