<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_H trkhch hng_loading (13)</name>
   <tag></tag>
   <elementGuidId>860dc16f-bf6f-4796-a794-69e48e61c8b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.icon_header.relative > div > img.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#v3_header >> internal:role=link[name=&quot;1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2cce85f9-30b4-4346-a494-d8015e6d6a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/icon_header__cart.png</value>
      <webElementGuid>6150187f-d636-4864-89a0-bf5f2449adc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>0421354d-ce5a-4cd8-b2b5-53c045c3e082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b4ef2a2-4b16-4de9-97a2-1681fe3b069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v4_inf_right_header&quot;]/div[@class=&quot;item_header item_header_giohang minicart-wrapper&quot;]/a[@class=&quot;icon_header relative&quot;]/div[1]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>e5213ba6-8447-4dcd-a067-d57b45ecd52a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      <webElementGuid>767fd627-3c14-42b0-8a62-97d37a9d135e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/icon_header__cart.png')]</value>
      <webElementGuid>3e86ab3f-094f-4bd9-9432-ec959c6e5b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>7d932ceb-49bf-4f4f-b175-ea0563116e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/icon_header__cart.png']</value>
      <webElementGuid>23ac54bd-e26e-4455-aa77-d5513dba2e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
