<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ty Da Cht Mt Cocoon C Ph k Lk 150ml_img_7b1959</name>
   <tag></tag>
   <elementGuidId>bb78cd2e-c9b5-4b94-98a7-7301d4728194</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > div.item_sp_hasaki.width_common.relative > a.v3_thumb_common_sp.relative > img.img_thumb.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li[6]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;26%&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b16a934b-de42-4af9-b65e-ce99b69792a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_thumb lazy loaded</value>
      <webElementGuid>e8b739c5-9fe0-46de-9f69-a7f44302895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-bong-tay-trang-hotosu-cao-cap-150-mieng_LiLeKqnqxkZ2ar83_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>0889554e-9b57-4b59-a061-ee6eb2ec65a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>imgError(this);</value>
      <webElementGuid>0b248271-b40d-40b6-8672-a6cf682fb65d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-bong-tay-trang-hotosu-cao-cap-150-mieng_LiLeKqnqxkZ2ar83_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>20232646-ba5c-4818-a126-8fcd7b5b5393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e17fd1d8-e299-4ea8-b8a3-69b1df5f42a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4432f29d-e560-4efa-a0b5-4d4c99480d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giatot_daily&quot;)/div[@class=&quot;width_common&quot;]/div[@class=&quot;flexslider&quot;]/div[@class=&quot;flex-viewport&quot;]/ul[@class=&quot;slides&quot;]/li[6]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;img_thumb lazy loaded&quot;]</value>
      <webElementGuid>6c5b599c-97ea-4dc3-9fec-18990f5adb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li[6]/div/a/img</value>
      <webElementGuid>484151c7-8d7d-4f79-8ba9-c768b66ea513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-bong-tay-trang-hotosu-cao-cap-150-mieng_LiLeKqnqxkZ2ar83_img_220x220_0dff4c_fit_center.png')]</value>
      <webElementGuid>d5d65fae-5810-42cb-9a59-9ce6bcc41df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a/img</value>
      <webElementGuid>028165f9-32f8-4968-92e6-fbcf8e8e0637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-bong-tay-trang-hotosu-cao-cap-150-mieng_LiLeKqnqxkZ2ar83_img_220x220_0dff4c_fit_center.png']</value>
      <webElementGuid>15962965-acbf-4b75-9fcb-22608181d1dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
