<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Retinol_loaded</name>
   <tag></tag>
   <elementGuidId>8ff79c9d-6d8c-4d39-b0b6-278fcd79dea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.icon_header >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6f0d6cc7-8461-4af9-87ea-121f7fe3147d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/icon_header__login.png</value>
      <webElementGuid>23b36b3d-c831-4a5e-b185-2035cb08420f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>f8d3b873-5217-41fc-b4f7-585ab2e7ecff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0f74a686-f8f4-4c7e-9c2a-52ea38af5d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v4_inf_right_header&quot;]/div[@class=&quot;item_header item_login&quot;]/a[@class=&quot;icon_header&quot;]/img[@class=&quot;loaded&quot;]</value>
      <webElementGuid>85d08dbc-aa5f-443f-8587-8366b4d54e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/a/img</value>
      <webElementGuid>ee867d34-0ba5-4fb5-b122-48209c7cfca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/icon_header__login.png')]</value>
      <webElementGuid>a9ef7e26-1296-4ea3-8578-9b7128ee0c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/a/img</value>
      <webElementGuid>69fac261-de52-4fcf-a6f7-143c8c1ee363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/icon_header__login.png']</value>
      <webElementGuid>2c42264e-baea-4e15-98e2-95ff5c32a2c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
