<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Retinol_loading</name>
   <tag></tag>
   <elementGuidId>acbcbeb0-ff08-49aa-89d2-324b28ce1bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.icon_header > img.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.icon_header > .loading >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d8cdaa47-506e-418c-8582-da685688d1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/icon_header__login.png</value>
      <webElementGuid>03e596af-6f93-4d7e-82ff-3fa288df0479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>91e11b66-9891-4107-a68d-f9573b9a7924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea66b754-8685-4538-955e-096817248662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v4_inf_right_header&quot;]/div[@class=&quot;item_header item_login user_login&quot;]/span[@class=&quot;icon_header&quot;]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>1d6051ef-76a3-4b52-a1f4-89467d88e003</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div/span/img</value>
      <webElementGuid>124b92ec-24c8-4e75-a7af-8376788796f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/icon_header__login.png')]</value>
      <webElementGuid>26f8e517-229f-45ac-a782-153d7b47ea75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>b591170f-c23c-4f57-b269-de2bb10dacc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/icon_header__login.png']</value>
      <webElementGuid>182670c3-87e1-4103-bf5f-00607cf7d6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
