<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Sa Ra Mt CeraVe Sch Su Cho Da Thng n Da_5b3fcc</name>
   <tag></tag>
   <elementGuidId>ef9a6ccd-f9fa-4d21-b911-dfb35291ac89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > div.item_sp_hasaki.width_common.relative > a.v3_thumb_common_sp.relative > img.img_thumb.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li[2]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;51%&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0582ca8a-4ae7-4d08-a7d8-617b61c91845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img_thumb lazy loaded</value>
      <webElementGuid>df6c4071-3fce-4fe1-b5f5-c0b4371c8ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-hong-khong-mui-klairs-danh-cho-da-nhay-cam-180ml_toCy1zUqJcsUhZyV_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>db29dc9b-5be2-484f-a70e-40431b7640fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>imgError(this);</value>
      <webElementGuid>6833b37c-8b3f-4314-9845-7ec8b03ebdef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-hong-khong-mui-klairs-danh-cho-da-nhay-cam-180ml_toCy1zUqJcsUhZyV_img_220x220_0dff4c_fit_center.png</value>
      <webElementGuid>6f4423a1-7a75-41be-854b-9d9a08e41e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7f434bad-8f4b-4ebc-b514-5ca2177475b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3fc92204-653e-4e57-bf6e-1d5a689db307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;giatot_daily&quot;)/div[@class=&quot;width_common&quot;]/div[@class=&quot;flexslider&quot;]/div[@class=&quot;flex-viewport&quot;]/ul[@class=&quot;slides&quot;]/li[2]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;img_thumb lazy loaded&quot;]</value>
      <webElementGuid>424649f7-b3f3-4c8f-8a1f-43d572c9a817</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='giatot_daily']/div[2]/div/div[2]/ul/li[2]/div/a/img</value>
      <webElementGuid>e390c07f-2df7-4d2a-b6b8-918278ea24b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-hong-khong-mui-klairs-danh-cho-da-nhay-cam-180ml_toCy1zUqJcsUhZyV_img_220x220_0dff4c_fit_center.png')]</value>
      <webElementGuid>a3e52a60-9aa2-46b7-b93d-0c8415d75467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/a/img</value>
      <webElementGuid>ccbc50e2-2168-4dc9-98cb-c8ed401ab7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-nuoc-hoa-hong-khong-mui-klairs-danh-cho-da-nhay-cam-180ml_toCy1zUqJcsUhZyV_img_220x220_0dff4c_fit_center.png']</value>
      <webElementGuid>4d053643-3096-4f42-8c2a-91a20d12a458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
