<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_H Tr Tr Mn_lazy loaded</name>
   <tag></tag>
   <elementGuidId>de00e513-9ced-4fe2-84c5-f0b48eeaf808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.top_big_search > a > img.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box_top_search_v2']/div[2]/div/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.top_big_search > a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52be7975-f1a4-4fc5-9e15-5f4192a7420c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/img/category/cate-chong-nang-da-mat.jpg</value>
      <webElementGuid>b76d34dc-e72f-4026-899f-d1a698f65204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://hasaki.vn/img/category/cate-chong-nang-da-mat.jpg</value>
      <webElementGuid>3e8ea830-c451-4610-8004-29b2467132ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>ecc4fcf2-70a8-42b9-94ac-38e8b30a2038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5852f316-c727-471e-b445-34b335866c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box_top_search_v2&quot;)/div[@class=&quot;content_box_common width_common&quot;]/div[@class=&quot;list_top_search row&quot;]/div[@class=&quot;item_top_search&quot;]/div[@class=&quot;top_big_search&quot;]/a[1]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>b274f00c-2a18-44e9-b539-e670bf8fbd3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box_top_search_v2']/div[2]/div/div/div/a/img</value>
      <webElementGuid>438f479a-e3fc-4494-92b4-257b9330c8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/img/category/cate-chong-nang-da-mat.jpg')]</value>
      <webElementGuid>27bdca83-b676-4993-945b-6dcdb82e1d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div/a/img</value>
      <webElementGuid>8c9c46ff-e1de-4745-81a8-7a60f5d55258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/img/category/cate-chong-nang-da-mat.jpg']</value>
      <webElementGuid>69513269-b16b-4582-a94e-e686138ac1ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
