<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mua L C Qu_lazy loaded</name>
   <tag></tag>
   <elementGuidId>931b6a53-ac0d-4532-b919-d6722bd2736e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.item_category_top.item_category_top_6 > a > span.icon_lam_category_top > img.lazy.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='box_icon_category']/div/div/div[7]/a/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Đặt Hẹn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c6d4b6d6-92f8-4c17-a04f-e6f939c487e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>imgError(this)</value>
      <webElementGuid>f6cff78e-072c-4363-9d56-4bde709298bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy loaded</value>
      <webElementGuid>d470dc84-55d3-4a0d-8167-230dcbf80c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png</value>
      <webElementGuid>7c4b92ea-2ce2-4100-be7a-3c8b47352bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png</value>
      <webElementGuid>eebf416b-ebe1-4129-8993-0d93582dbc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cee02e3-fdd4-4c2c-84b4-1af107e05bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;box_icon_category&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;list_category_top&quot;]/div[@class=&quot;item_category_top item_category_top_6&quot;]/a[1]/span[@class=&quot;icon_lam_category_top&quot;]/img[@class=&quot;lazy loaded&quot;]</value>
      <webElementGuid>064efcc7-adec-45c0-8bc0-53370ee31b85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='box_icon_category']/div/div/div[7]/a/span/img</value>
      <webElementGuid>a0ede25a-646b-460c-8646-50ae2852a1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png')]</value>
      <webElementGuid>6f8de8c8-8d19-423b-8293-81c555bf364f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/span/img</value>
      <webElementGuid>532bd10f-35fc-46ff-bcff-3eb46a49d278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/hasaki-dat-hen.png']</value>
      <webElementGuid>2d78b74d-87ec-4484-af95-0ecf5cfea642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
