<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Toner_icon_search loading</name>
   <tag></tag>
   <elementGuidId>baae48bf-0223-4166-85f4-857d8b92b59c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='search_mini_form']/div[2]/div/div/div[2]/button/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.icon_search.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ec042b4-6d02-428c-8f86-9bec3ea2a14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://hasaki.vn/v3/images/icons/search_icon.svg</value>
      <webElementGuid>4dc2f04d-4bbf-44f7-825f-98b80e75e75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon_search loading</value>
      <webElementGuid>5a46c121-8d05-4038-929d-250fecd14882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>22017f6d-1a16-47e2-b922-c6b9db7131f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search_mini_form&quot;)/div[@class=&quot;v3_block_search_header&quot;]/div[@class=&quot;relative width_common&quot;]/div[@class=&quot;v3_block_input_search width_common&quot;]/div[@class=&quot;actions&quot;]/button[@class=&quot;btn_submit_search&quot;]/img[@class=&quot;icon_search loading&quot;]</value>
      <webElementGuid>48782868-c166-4e01-8071-61d06d0bccc5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div[2]/div/div/div[2]/button/img</value>
      <webElementGuid>a3f70450-f727-4596-960a-8b966daa2455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://hasaki.vn/v3/images/icons/search_icon.svg')]</value>
      <webElementGuid>0a016644-d984-40ac-92f2-7a83a38a6f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/img</value>
      <webElementGuid>10cd1fe2-c4f7-4941-9b16-81075f5fe727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://hasaki.vn/v3/images/icons/search_icon.svg']</value>
      <webElementGuid>fe658380-2933-4d72-8381-73cfee653684</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
