<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Toner_q</name>
   <tag></tag>
   <elementGuidId>3a1a14f5-8394-43c3-a597-b024ebf31376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Tìm sản phẩm, thương hiệu bạn mong muốn...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcc816ed-31c6-475f-9a8f-1ec9d4190635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>171186cb-f537-4572-a81f-5a0e6745ff18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm, thương hiệu bạn mong muốn...</value>
      <webElementGuid>eb4128e8-d679-45c8-ba97-3aaa334df7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input_search</value>
      <webElementGuid>e64e1f2b-fef0-4d9d-beee-f9358de95dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
      <webElementGuid>56145489-1454-45d5-88e0-50388b8edcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-box-parent</name>
      <type>Main</type>
      <value>#block_suggest_search</value>
      <webElementGuid>48b1b5c4-6a1b-484d-8609-fc8b462d3706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fe1976ef-1c57-479d-8958-841322cc4bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4ab496d-2f11-482b-9b93-c2446b51973d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>campaign-rel</name>
      <type>Main</type>
      <value>[{&quot;label&quot;:&quot;Deal 2K áp dụng CN261 TP. Đồng Xoài, Bình Phước (09 - 15/06)&quot;,&quot;url&quot;:&quot;https://hasaki.vn/campaign/khai-truong-chi-nhanh-261?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=khai-truong-chi-nhanh-261&amp;utm_term=khai-truong-chi-nhanh-261_09062025&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1750006740,&quot;start_time&quot;:1749402000},{&quot;label&quot;:&quot;NEW! Miếng Dán Ngực Hotosu Siêu Bám Dính 12H - Chỉ 55K&quot;,&quot;url&quot;:&quot;https://hasaki.vn/thuong-hieu/hotosu.html?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=mieng-dan-nguc-hotosu-launching&amp;utm_term=mieng-dan-nguc-hotosu-launching_26052025&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1750006740,&quot;start_time&quot;:1749056400},{&quot;label&quot;:&quot;Mua Nước Hoa Cao Cấp Chính Hãng - Chọn Ngay Hasaki&quot;,&quot;url&quot;:&quot;https://hasaki.vn/danh-muc/nuoc-hoa-cao-cap-c2286.html?utm_medium=cpc&amp;utm_source=top_search&amp;utm_campaign=mua-nuoc-hoa-cao-cap-tai-hasaki-la-co-qua&amp;utm_term=mua-nuoc-hoa-cao-cap-tai-hasaki-la-co-qua_20012025&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1767200340,&quot;start_time&quot;:1748192400},{&quot;label&quot;:&quot;Giảm 50% Ủ Trắng Các Vùng – Mua 5 Tặng 5&quot;,&quot;url&quot;:&quot;https://hasaki.vn/cam-nang/uu-dai-cuoi-nam-hasaki-clinic-tro-gia-den-50-4778.html?utm_source=website&amp;utm_medium=keyword_thanh_search&amp;utm_campaign=uu_dai_triet_long_200K_24052024&quot;,&quot;image&quot;:&quot;https://media.hcdn.vn/&quot;,&quot;end_time&quot;:1767200340,&quot;start_time&quot;:1735664400}]</value>
      <webElementGuid>83197a2e-bcbd-4db7-9d24-059e665cd15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)</value>
      <webElementGuid>eeb2825a-3019-4709-806b-7b22ac708627</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search']</value>
      <webElementGuid>443b8eb6-1e33-4ae2-87bd-e42a964aca0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div[2]/div/div/div/input</value>
      <webElementGuid>675baf2e-c342-4379-8ec9-eaa1ff214384</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>f639151d-dbc2-451b-b03e-629a4df9d1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = 'Tìm sản phẩm, thương hiệu bạn mong muốn...' and @name = 'q']</value>
      <webElementGuid>1d9aac51-96f9-4d93-826e-51cce51ffc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = 'Mua Nước Hoa Cao Cấp Chính Hãng - Chọn Ngay Hasaki' and @name = 'q']</value>
      <webElementGuid>9d8b0a97-23a3-4a75-9871-5dda0fc516b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = 'Khai Trương CN261 TP. Đồng Xoài, Bình Phước | Deal 2K (Chỉ 08/06)' and @name = 'q']</value>
      <webElementGuid>6572843d-77d7-45e2-b1ef-2c70a831c1fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @placeholder = '6.6 Ở Đâu Rẻ - Hasaki Rẻ Hơn' and @name = 'q']</value>
      <webElementGuid>d5150578-3cbf-49a7-ae2e-89bc5e0d55ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
