<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chn Tnh TP, Qun HuynCaret Down Icon (1)</name>
   <tag></tag>
   <elementGuidId>eecfec36-6c63-4637-94ad-f97befab5f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=':r1j:-form-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chọn Tỉnh/ TP, Quận/ HuyệnCaret Down Icon&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11e013c0-19bb-4eb5-ba7c-c810d62eaa1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:bg-background disabled:text-ring border border-input hover:bg-accent hover:text-accent-foreground px-4 py-2 w-full h-11 border-none justify-between text-sm transition-color rounded-[10px] bg-background shadow-none text-muted-foreground</value>
      <webElementGuid>30af65cb-5a90-427b-aa1f-603b9e00f95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>96ba8918-e237-4298-b214-a46fad8d7836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7d826c70-7728-4c93-af29-57ce3d271cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1j:-form-item</value>
      <webElementGuid>e49d9a2f-1837-4287-939d-ae801dca61ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1j:-form-item-description</value>
      <webElementGuid>aed6a231-b437-4cb2-a57b-5df10a11d7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>540a6208-f5b2-4522-86ae-900c229ebace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea6b3f12-95b6-4274-aaaf-84e7cd65afac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>aaad8909-c318-485c-a348-a54921015f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1k:</value>
      <webElementGuid>2983944d-4178-482a-9e37-0eee34529e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>ca01d0c8-65dd-43b6-8364-601f05275bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Tỉnh/ TP, Quận/ HuyệnCaret Down Icon</value>
      <webElementGuid>fe4e0517-d93b-4d51-8fb8-f5930fe2adcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1j:-form-item&quot;)</value>
      <webElementGuid>bee1cabf-0f08-41f3-b873-c15c69f6d910</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1j:-form-item']</value>
      <webElementGuid>16c2647b-f4af-4699-b7ec-d654423c3d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ru:']/div/form/section/div[2]/button</value>
      <webElementGuid>f3425b54-f25e-49b8-9e83-4161812600a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identification Card Icon'])[1]/following::button[1]</value>
      <webElementGuid>75fa6dfc-4b54-4286-b340-496b05486346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm địa chỉ mới'])[2]/following::button[1]</value>
      <webElementGuid>d8f68eec-e785-4863-9e8b-ef45b43aebd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chọn Tỉnh/ TP, Quận/ Huyện']/parent::*</value>
      <webElementGuid>0f8e6c63-8c35-4509-9160-805ca876be6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0d46d828-6665-4918-813b-ce9ef817f61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1j:-form-item' and @type = 'button' and (text() = 'Chọn Tỉnh/ TP, Quận/ HuyệnCaret Down Icon' or . = 'Chọn Tỉnh/ TP, Quận/ HuyệnCaret Down Icon')]</value>
      <webElementGuid>0a81449b-e4ae-4ff5-9110-a9a1f33eba1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
