<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chn Phng XCaret Down Icon</name>
   <tag></tag>
   <elementGuidId>532f2734-24b8-4ccd-805c-e27101abe908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=':r1p:-form-item']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chọn Phường/ XãCaret Down Icon&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46b3d80f-fbd5-4736-b7a6-cb78a57970e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:bg-background disabled:text-ring border border-input hover:bg-accent hover:text-accent-foreground px-4 py-2 w-full h-11 border-none justify-between transition-color rounded-[10px] bg-background shadow-none text-muted-foreground text-sm</value>
      <webElementGuid>4601caaa-2506-4a29-80f6-df7d2cfa3598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>93959ddf-39ca-4459-af4a-f7d9931d22d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2d1885ba-13da-4b4e-973c-14a8cbfca458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1p:-form-item</value>
      <webElementGuid>856f2db9-890b-4a26-bb92-ee438ae55014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1p:-form-item-description</value>
      <webElementGuid>5bddae73-f46f-43d4-9e45-afa518658e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fab79a81-f399-404b-aa8e-18df33b377c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>395f0e29-b131-409e-9b4b-fc8a67d44216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>736d11fd-c956-4ddc-ac8a-e1ad990a50f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1q:</value>
      <webElementGuid>521b714e-d315-4d8c-9ac9-8700efadeb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>443fed2f-454b-43dc-bc27-3d1bd9b27562</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Phường/ XãCaret Down Icon</value>
      <webElementGuid>eb173c0f-1d6c-4553-ba8e-d25b4b6e7866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1p:-form-item&quot;)</value>
      <webElementGuid>e9419b1d-bd1d-4dc0-8370-0b5bbd276698</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1p:-form-item']</value>
      <webElementGuid>c66ba291-b584-4339-baa6-dd8d8ca280e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ru:']/div/form/section/div[3]/button</value>
      <webElementGuid>86abd1c8-cc5e-4400-ab5b-fc95ebf26ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caret Down Icon'])[1]/following::button[1]</value>
      <webElementGuid>76164207-842d-44d0-92ba-7e5b915e7d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn Tỉnh/TP, Quận/ Huyện và Phường/ xã trước khi nhập Số nhà + Tên Đường'])[1]/preceding::button[1]</value>
      <webElementGuid>295c739c-2c41-43c1-8416-970a8045b7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chọn Phường/ Xã']/parent::*</value>
      <webElementGuid>d66ce0a3-2a47-4880-b7ef-55f8b28eb9b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5b166364-5dd3-460b-8eb1-9791f06930f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1p:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>31ddeba1-4d55-49b6-97a7-579aeaabd9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r25:-form-item']</value>
      <webElementGuid>9b035bd1-eca1-4b83-8e6c-f3d2884a0030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r25:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>0ad3edea-f3d0-4887-baad-ba8686a191a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1l:-form-item']</value>
      <webElementGuid>c41c1511-65d1-46ca-bee2-01719f36d891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1l:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>e595d9d7-02d2-4e0a-8094-12fda0194c20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
