<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Chn Phng XCaret Down Icon</name>
   <tag></tag>
   <elementGuidId>532f2734-24b8-4ccd-805c-e27101abe908</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id=':r1l:-form-item']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Chọn Phường/ XãCaret Down Icon&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f5c4470c-b4a6-4cc4-a3ac-0989849cab84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center font-medium transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:bg-background disabled:text-ring border border-input hover:bg-accent hover:text-accent-foreground px-4 py-2 w-full h-11 border-none justify-between transition-color rounded-[10px] bg-background shadow-none text-muted-foreground text-sm</value>
      <webElementGuid>246d7baf-ecae-418a-9c1e-0e04a9556ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fd72e702-ba3d-40bd-9350-5e2b5a84fa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d4c117af-a849-47ee-ac1c-f6b34cdc1816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1l:-form-item</value>
      <webElementGuid>66f12209-f65f-47bf-8860-59bb9f2118b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r1l:-form-item-description</value>
      <webElementGuid>5becb282-b994-4436-98eb-caeffea29203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4b1c481c-5028-44e6-be7d-5286ac889ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d3a6a3ee-eaec-4cd9-a293-8ce534fba2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>4f02ec7f-2310-4403-aa0b-90bf82f40103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r1m:</value>
      <webElementGuid>e73374ab-480b-43e8-956d-795a71884e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>47e0b2b1-51ce-4b32-8cda-378dfa741135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Chọn Phường/ XãCaret Down Icon</value>
      <webElementGuid>df548ca9-d5c9-49d0-819c-d80907347049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1l:-form-item&quot;)</value>
      <webElementGuid>621af03b-8a3c-4f56-b619-b8daa79c6019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1l:-form-item']</value>
      <webElementGuid>edeec080-d04a-4a54-a23a-086592a01594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ru:']/div/form/section/div[3]/button</value>
      <webElementGuid>3edaf749-83b3-4183-b3dc-150ba278560d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caret Down Icon'])[1]/following::button[1]</value>
      <webElementGuid>ffbcc102-e50c-4f26-9325-67513f64635f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn Tỉnh/TP, Quận/ Huyện và Phường/ xã trước khi nhập Số nhà + Tên Đường'])[1]/preceding::button[1]</value>
      <webElementGuid>a0aa8afb-c00b-4d45-82e7-a5c280fb2c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Chọn Phường/ Xã']/parent::*</value>
      <webElementGuid>39491972-aa3a-4ad1-99d0-0b09960a0add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>cc5777a0-ce6a-41d5-b6fb-5defcbe6c161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1l:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>46fa49d3-132c-4798-85e2-d47971696a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1h:-form-item']</value>
      <webElementGuid>b9f0bf7d-7b4b-40a8-a13d-ec9aa04b3db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1h:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>4df6acb8-4cbd-4e52-bdb7-de0435a82103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r1p:-form-item']</value>
      <webElementGuid>bb0954e7-b70e-495c-8bf0-d9ff77bd610f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r1p:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>31e6105f-faad-4aff-b890-bf6c5928546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id=':r25:-form-item']</value>
      <webElementGuid>9b035bd1-eca1-4b83-8e6c-f3d2884a0030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = ':r25:-form-item' and @type = 'button' and (text() = 'Chọn Phường/ XãCaret Down Icon' or . = 'Chọn Phường/ XãCaret Down Icon')]</value>
      <webElementGuid>0ad3edea-f3d0-4887-baad-ba8686a191a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
