<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_a ch khng th cha ton b l khong trng</name>
   <tag></tag>
   <elementGuidId>ff322dfc-94dd-45f7-afaa-79ad05085cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r1j:-form-item-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Địa chỉ không thể chứa toàn bộ là khoảng trắng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>907d4cf5-d70f-4a93-b125-a01d96c64910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1j:-form-item-message</value>
      <webElementGuid>4ac1fd81-f2d7-4598-b702-761b7f2a6849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[0.8rem] font-medium text-destructive</value>
      <webElementGuid>5e1ef1ce-4e3a-4f7c-94a6-9160e648807e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Địa chỉ không thể chứa toàn bộ là khoảng trắng</value>
      <webElementGuid>7f99fb96-80f0-4b41-8e4f-e8d7e1b881d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1j:-form-item-message&quot;)</value>
      <webElementGuid>fad27e32-71e5-484a-b78d-af18a75a77d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r1j:-form-item-message']</value>
      <webElementGuid>581be9ec-8312-4788-9574-4340eb3b827f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ru:']/div/form/section/div[4]/p</value>
      <webElementGuid>4708e871-3ea0-4e83-ab52-0e6b8cfd6635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caret Down Icon'])[2]/following::p[1]</value>
      <webElementGuid>3c2fded3-f066-4119-8e19-151540862d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::p[3]</value>
      <webElementGuid>05e8a0d7-cc18-4448-85c1-3c6384b50096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Di chuyển sang trái'])[1]/preceding::p[3]</value>
      <webElementGuid>b6b6dcfb-9c14-4fed-bfd3-242ff8b2de0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Địa chỉ không thể chứa toàn bộ là khoảng trắng']/parent::*</value>
      <webElementGuid>f22a831c-0095-46dc-934e-ec96a1d0925d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>e6c7799e-9aca-4034-9792-420b733ade5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r1j:-form-item-message' and (text() = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng' or . = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng')]</value>
      <webElementGuid>a5f9cb08-7dec-438e-bc7a-2112ae45f4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r1r:-form-item-message']</value>
      <webElementGuid>1f19c10c-7463-4e41-82d7-733d1cae46f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r1r:-form-item-message' and (text() = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng' or . = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng')]</value>
      <webElementGuid>6bd7c388-a178-4be9-af67-5144ee9f8f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r27:-form-item-message']</value>
      <webElementGuid>bdc1345a-b061-4daa-a701-625ca077751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r27:-form-item-message' and (text() = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng' or . = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng')]</value>
      <webElementGuid>75fe8581-021b-4c88-8da7-a04c07cdd0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
