<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_a ch khng th cha ton b l khong trng</name>
   <tag></tag>
   <elementGuidId>ff322dfc-94dd-45f7-afaa-79ad05085cc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r27:-form-item-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Địa chỉ không thể chứa toàn bộ là khoảng trắng&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b24d42ef-a5b1-4861-bb29-928245127436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r27:-form-item-message</value>
      <webElementGuid>1c34e44f-4553-4063-be8b-189d8ac7eef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[0.8rem] font-medium text-destructive</value>
      <webElementGuid>de9ffcb3-2e77-41e5-ace1-8f103eaf519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Địa chỉ không thể chứa toàn bộ là khoảng trắng</value>
      <webElementGuid>203bfeb7-4946-431e-ade6-f379fa5ebb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r27:-form-item-message&quot;)</value>
      <webElementGuid>8b4014f0-ae06-4519-8b28-85c79c107f14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r27:-form-item-message']</value>
      <webElementGuid>bdc1345a-b061-4daa-a701-625ca077751c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:ru:']/div/form/section/div[4]/p</value>
      <webElementGuid>226ca576-542e-407b-b309-fc415f8cf23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caret Down Icon'])[2]/following::p[1]</value>
      <webElementGuid>d8a0f15f-a4b4-436f-a1b4-43ef8abe1d4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='←'])[1]/preceding::p[3]</value>
      <webElementGuid>abcd63d2-5f17-46fa-bce3-923b02e7abf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Di chuyển sang trái'])[1]/preceding::p[3]</value>
      <webElementGuid>04676a38-3a73-48c4-9234-ac2b288a73a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Địa chỉ không thể chứa toàn bộ là khoảng trắng']/parent::*</value>
      <webElementGuid>9d36031f-46ec-4d57-bf29-58e1a75e2a5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>5b07b2bb-2226-4155-931a-6a1454935842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r27:-form-item-message' and (text() = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng' or . = 'Địa chỉ không thể chứa toàn bộ là khoảng trắng')]</value>
      <webElementGuid>75fe8581-021b-4c88-8da7-a04c07cdd0db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
