<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Nu_m-auto rounded-2px</name>
   <tag></tag>
   <elementGuidId>33f63c8c-587f-4dfd-81f7-a54224aeaac5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Nâu']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Nâu&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c4c36426-2d01-42b0-97bb-b4906fd86b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-auto rounded-[2px]</value>
      <webElementGuid>d8e7cb8d-80ae-4019-8ec3-1b8ee1804da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nâu</value>
      <webElementGuid>78c4cd3f-5c47-4740-bbc9-9a1ae42e3bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>7b09f60d-eb8f-4173-8136-bff149906ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>15ac487b-6698-40a2-9e32-27898218a68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/p/r/promotions-auto-dau-goi-kho-girlz-only-cho-toc-nau-toi-mau-200ml_xrgBeoZ9H66yhXxD_img_38x38_2b8932_fit_center.png</value>
      <webElementGuid>23dab344-f91e-4ec5-8559-9eea264a53a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;min-h-screen bg-background font-sans antialiased __variable_d65c78&quot;]/div[@class=&quot;min-h-screen w-full&quot;]/div[@class=&quot;max-w-[1400px] m-auto container&quot;]/div[@class=&quot;flex gap-2.5&quot;]/div[@class=&quot;w-full flex flex-col gap-2.5 min-h-[20px] [&amp;>div:last-child]:h-full&quot;]/div[@class=&quot;flex gap-5 bg-white&quot;]/div[@class=&quot;w-full pt-2.5&quot;]/div[@class=&quot;pb-2.5 pr-2.5&quot;]/div[5]/div[@class=&quot;mb-[5px]&quot;]/div[@class=&quot;w-full flex flex-wrap gap-2.5 overflow-hidden overflow-x-auto text-xs&quot;]/a[@class=&quot;relative text-center shrink-0 border-[1px] border-[#ccc] rounded-[2px] overflow-hidden&quot;]/img[@class=&quot;m-auto rounded-[2px]&quot;]</value>
      <webElementGuid>8ca62174-1b72-4ad6-b02c-410b3aa910fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Nâu']</value>
      <webElementGuid>b0501b74-b63e-42dc-9e20-70fb98c0790b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/img</value>
      <webElementGuid>03f39e93-47fc-4530-bf2f-d1fb56998424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Nâu' and @src = 'https://media.hcdn.vn/catalog/product/p/r/promotions-auto-dau-goi-kho-girlz-only-cho-toc-nau-toi-mau-200ml_xrgBeoZ9H66yhXxD_img_38x38_2b8932_fit_center.png']</value>
      <webElementGuid>604ebad2-c355-4ccb-aa96-156dd18490b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
