<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hin th 60_photo image img_thumb_sub loading</name>
   <tag></tag>
   <elementGuidId>225c50eb-6b58-4f81-b65c-c9100dc2ab6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.photo.image.img_thumb_sub.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_sp_col_right']/div[5]/div/div/a/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#list_sp_col_right >> internal:role=link[name=&quot;Tặng: Sữa Rửa Mặt CeraVe Sạch Sâu 30ml (SL có hạn) Tặng: Sữa Rửa Mặt CeraVe Sạch Sâu 30ml (SL có hạn)&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6331c0f2-3166-4a82-985f-b8d20b0ff568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>photo image img_thumb_sub loading</value>
      <webElementGuid>f6876131-6e68-46f2-8a67-f07db81901b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg</value>
      <webElementGuid>e88a2074-419f-442a-9e74-0d1ac6b2b90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>01723436-4e3f-4090-94f5-a8641d757895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sp_col_right&quot;)/div[@class=&quot;ProductGrid__grid width_common&quot;]/div[@class=&quot;ProductGridItem__itemOuter&quot;]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;photo image img_thumb_sub loading&quot;]</value>
      <webElementGuid>2e614f8b-2022-4f09-8ec9-08c0b8705adf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sp_col_right']/div[5]/div/div/a/img[2]</value>
      <webElementGuid>3c545daf-8a15-45f9-bafe-8e13c7f64685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg')]</value>
      <webElementGuid>90272b94-3cc6-4811-997a-2d1b8fd31e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img[2]</value>
      <webElementGuid>54777ab4-6bdb-4946-920e-aacc70ecd8be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg']</value>
      <webElementGuid>dbe61a53-6b73-4188-8676-9e6f7132d68f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
