<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Hin th 60_photo image img_thumb_sub loading</name>
   <tag></tag>
   <elementGuidId>225c50eb-6b58-4f81-b65c-c9100dc2ab6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_sp_col_right']/div[5]/div/div/a/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.photo.image.img_thumb_sub.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#list_sp_col_right >> internal:role=link[name=&quot;Tặng: Sữa Rửa Mặt CeraVe Sạch Sâu 30ml (SL có hạn) Tặng: Sữa Rửa Mặt CeraVe Sạch Sâu 30ml (SL có hạn)&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dd6a059b-43f1-40b1-8430-9e43bec44e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>photo image img_thumb_sub loading</value>
      <webElementGuid>08c82dc4-d28a-4dcf-86db-10b8430fac47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg</value>
      <webElementGuid>27327240-5370-47cd-b05d-05ccc3edae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>261e9b3e-7a96-45f9-aee0-93c98d7815fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sp_col_right&quot;)/div[@class=&quot;ProductGrid__grid width_common&quot;]/div[@class=&quot;ProductGridItem__itemOuter&quot;]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;photo image img_thumb_sub loading&quot;]</value>
      <webElementGuid>c2db3efe-13d5-402d-b29c-691dcb9292c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sp_col_right']/div[5]/div/div/a/img[2]</value>
      <webElementGuid>3c08f260-bf4e-4fd3-9d1f-2c389291de99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg')]</value>
      <webElementGuid>f2dda42c-3cd5-4139-833c-b43aa08d5173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img[2]</value>
      <webElementGuid>6c2adceb-9cb0-4051-b7d1-c24f3afc0bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/f/a/facebook-dynamic-sua-rua-mat-cerave-sach-sau-cho-da-thuong-den-da-dau-473ml-1741158164_img_300x300_b798dd_fit_center.jpg']</value>
      <webElementGuid>fcea06fc-a527-4045-a9ca-bbcd6ca1c99b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
