<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Bill Cerave 399K Tng Gi tt nghip tr gi _a5c310</name>
   <tag></tag>
   <elementGuidId>e10d1be7-2699-45b6-94be-aef6a8e1fb02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list_sp_col_right']/div[5]/div[3]/div/a/img[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > .item_sp_hasaki > .v3_thumb_common_sp</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>78e7d7ee-c5e3-49bc-80aa-fa4a5e57c1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>photo image img_thumb_sub loading</value>
      <webElementGuid>ff2fe8b7-853f-405d-85d0-f01ed229a6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/catalog/product/t/e/tem-phu_211300007-1677730309_img_300x300_b798dd_fit_center.jpg</value>
      <webElementGuid>9795da88-65fb-44fb-b374-72735846d299</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bcff4b20-f277-439a-851d-c4bbf9e6aee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_sp_col_right&quot;)/div[@class=&quot;ProductGrid__grid width_common&quot;]/div[@class=&quot;ProductGridItem__itemOuter&quot;]/div[@class=&quot;item_sp_hasaki width_common relative&quot;]/a[@class=&quot;v3_thumb_common_sp relative&quot;]/img[@class=&quot;photo image img_thumb_sub loading&quot;]</value>
      <webElementGuid>9cacf09d-7cce-41c9-8312-bd39aac31667</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sp_col_right']/div[5]/div[3]/div/a/img[2]</value>
      <webElementGuid>ce044da5-5ef6-448f-bf36-cbbcbb559c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/catalog/product/t/e/tem-phu_211300007-1677730309_img_300x300_b798dd_fit_center.jpg')]</value>
      <webElementGuid>2dd4469b-6b87-43b1-8224-cbda1ca88761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img[2]</value>
      <webElementGuid>a5165a33-8117-4292-965c-ef61aa7f4a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/catalog/product/t/e/tem-phu_211300007-1677730309_img_300x300_b798dd_fit_center.jpg']</value>
      <webElementGuid>c73acf81-95f6-4bfb-9e40-b9a03bb7a337</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
