<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_140ml</name>
   <tag></tag>
   <elementGuidId>35ab9fbc-b18b-4be3-9ace-57e550e2188f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'140ml')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;140ml&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8de2a4dc-f8e0-42d3-9e31-a55d243ab673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative p-2.5 border-[1px] border-[#ccc] overflow-hidden</value>
      <webElementGuid>4c142604-1da3-4b9e-ae13-43edcddb786e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://hasaki.vn/san-pham/nuoc-tay-trang-bi-dao-cocoon-lam-sach-giam-dau-140ml-96273.html</value>
      <webElementGuid>133d325a-d025-49ec-9ffa-f2fdc28e2176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>140ml</value>
      <webElementGuid>181ca24b-ae2d-43b4-aae2-65c2e35a4d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;min-h-screen bg-background font-sans antialiased __variable_d65c78&quot;]/div[@class=&quot;min-h-screen w-full&quot;]/div[@class=&quot;max-w-[1400px] m-auto container&quot;]/div[@class=&quot;flex gap-2.5&quot;]/div[@class=&quot;w-full flex flex-col gap-2.5 min-h-[20px] [&amp;>div:last-child]:h-full&quot;]/div[@class=&quot;flex gap-5 bg-white&quot;]/div[@class=&quot;w-full pt-2.5&quot;]/div[@class=&quot;pb-2.5 pr-2.5&quot;]/div[5]/div[@class=&quot;mb-[5px]&quot;]/div[@class=&quot;w-full flex flex-wrap gap-2.5 overflow-hidden overflow-x-auto text-xs&quot;]/a[@class=&quot;relative p-2.5 border-[1px] border-[#ccc] overflow-hidden&quot;]</value>
      <webElementGuid>99074258-c288-4366-8914-5142c02a8156</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'140ml')])[2]</value>
      <webElementGuid>79f2c361-093f-4331-ad59-00ca6d046aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dung Tích'])[1]/following::a[3]</value>
      <webElementGuid>48996761-5cba-4843-a9a8-7ccadab7f070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Số lượng:'])[1]/preceding::a[3]</value>
      <webElementGuid>aa6c0da9-9604-44c3-86bc-b21c68f2d070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giao Nhanh Miễn Phí 2H'])[1]/preceding::a[3]</value>
      <webElementGuid>90e199c1-dd1b-4e90-9f11-608e69e51996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='140ml']/parent::*</value>
      <webElementGuid>14229f5e-26d3-457f-98a0-aebda925901f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://hasaki.vn/san-pham/nuoc-tay-trang-bi-dao-cocoon-lam-sach-giam-dau-140ml-96273.html')]</value>
      <webElementGuid>b0e5196b-ab87-4ca0-bd70-406bdc397555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[3]</value>
      <webElementGuid>b471e4c1-f63d-47cf-9d80-97e91e59a7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://hasaki.vn/san-pham/nuoc-tay-trang-bi-dao-cocoon-lam-sach-giam-dau-140ml-96273.html' and (text() = '140ml' or . = '140ml')]</value>
      <webElementGuid>b539b69b-7790-45cd-8b5d-473df9d323a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
