<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1630</name>
   <tag></tag>
   <elementGuidId>bc1b4bc7-c17f-4c68-b8e2-115687ccf69e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_input_time']/div[3]/div/div[16]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;16:30&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>324258c1-6081-41c2-ba44-adb8f52cf46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item_hours</value>
      <webElementGuid>f8c1b5ea-0bf7-40cc-adf0-1899fa39a16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1746610200</value>
      <webElementGuid>c391381d-9428-4fc9-86f3-55204620b43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16:30</value>
      <webElementGuid>68626cb5-7e59-4056-9143-57ee6284d7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_input_time&quot;)/div[@class=&quot;input_hours width_common&quot;]/div[@class=&quot;list_hours width_common&quot;]/div[@class=&quot;item_hours&quot;]</value>
      <webElementGuid>a6de876d-019e-420b-a9a2-20b3eaabd5fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_time']/div[3]/div/div[16]</value>
      <webElementGuid>8db8e77d-0637-433b-a198-38e2bc36c59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thứ 3'])[1]/following::div[18]</value>
      <webElementGuid>ee6f1630-1acb-49c7-ab93-9e9893e7973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thứ 2'])[1]/following::div[20]</value>
      <webElementGuid>270e3f3c-d49a-40c7-bacf-5d55c05b8fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/preceding::div[3]</value>
      <webElementGuid>74e6b06b-0865-4482-9876-905721bcc812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt hẹn'])[1]/preceding::div[3]</value>
      <webElementGuid>7228b0cb-f379-4991-a340-ddd3a5d6f34b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16:30']/parent::*</value>
      <webElementGuid>3c4581ac-33e7-4ab8-9bad-84ede8b1ea09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]</value>
      <webElementGuid>661e5261-2e2d-42b4-976f-cc0149e09b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '16:30' or . = '16:30')]</value>
      <webElementGuid>d9c2486c-239b-4912-809f-25ae4cce5f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
