<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1600</name>
   <tag></tag>
   <elementGuidId>ba1723c5-bab6-46c5-9f37-b14f53dea6e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_input_time']/div[3]/div/div[15]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;16:00&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b75135c4-58d5-4b44-93fc-0dc43eaf542d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item_hours</value>
      <webElementGuid>ccff453c-b283-49f0-a6d9-d12514250ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1746608400</value>
      <webElementGuid>9df69a27-0c5f-48c3-834a-45ed4b145a06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16:00</value>
      <webElementGuid>e6a69651-37b7-4c0d-a9ec-0218294179da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_input_time&quot;)/div[@class=&quot;input_hours width_common&quot;]/div[@class=&quot;list_hours width_common&quot;]/div[@class=&quot;item_hours&quot;]</value>
      <webElementGuid>b57c671f-f6b4-4ead-84fe-2dc762619717</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_time']/div[3]/div/div[15]</value>
      <webElementGuid>5a9c9bf8-1d5a-4a11-ac98-79026ccae227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thứ 3'])[1]/following::div[17]</value>
      <webElementGuid>bcb19e76-dfe3-4cb0-9848-21061d40f3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thứ 2'])[1]/following::div[19]</value>
      <webElementGuid>3a375375-b7a2-4e3d-8f51-3ad5d15166dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại'])[1]/preceding::div[4]</value>
      <webElementGuid>28bcd215-63d2-4eec-b02b-247a145932dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt hẹn'])[1]/preceding::div[4]</value>
      <webElementGuid>9e9a8a7d-6fbe-4397-afe1-38d67537e29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16:00']/parent::*</value>
      <webElementGuid>b0dc8f08-c20f-4b5c-b8ae-dbcd90f38922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]</value>
      <webElementGuid>f03c5a20-3792-4a09-81b2-80b36439bc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '16:00' or . = '16:00')]</value>
      <webElementGuid>a1d8826f-b9e2-4eb1-9945-a7b0225f45e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
