<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Chi nhnh 1_loading</name>
   <tag></tag>
   <elementGuidId>59ef2f94-c82a-42df-9422-5bf92c826881</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.thumb_chinhanh > img.loading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_input_chinhanh']/div[2]/div[2]/ul/li[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Chi nhánh 2 555 Đường 3 Tháng 2, P.8, Q.10, TP.HCM&quot;i >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>148bc101-cc2d-4e3f-97f1-8d8370da861a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/555-bathanghai.jpg</value>
      <webElementGuid>d7008f85-6b6a-426a-8e98-c94cb143ad2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>f532d686-b4ed-4c6f-bfc5-083fdb1a04c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7528e3ca-c536-4d7c-aa58-aeb100ba4619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e39567a7-aa67-4e97-b68f-96a6d13c84f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_input_chinhanh&quot;)/div[@class=&quot;list_chinhanh flexslider width_common space_bottom_10&quot;]/div[@class=&quot;flex-viewport&quot;]/ul[@class=&quot;slides&quot;]/li[2]/div[@class=&quot;item_chinhanh&quot;]/div[@class=&quot;thumb_chinhanh&quot;]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>073e9cfe-24ae-4a6e-a2b3-1151198bca63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_chinhanh']/div[2]/div[2]/ul/li[2]/div/div/img</value>
      <webElementGuid>ed5b8066-609b-4574-8999-a354b5cfcb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/img</value>
      <webElementGuid>4cbaf1f7-d6fc-416d-834f-df43cc58b928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/555-bathanghai.jpg']</value>
      <webElementGuid>42eca5cb-b277-44ca-965c-c82c13c6d13c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
