<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Chi nhnh 1_loaded</name>
   <tag></tag>
   <elementGuidId>ff0ee5a7-b053-44b6-b5d8-a167f051baed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.thumb_chinhanh > img.loaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block_input_chinhanh']/div[2]/div[2]/ul/li[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>li >> internal:has-text=&quot;Chi nhánh 2 555 Đường 3 Tháng 2, P.8, Q.10, TP.HCM&quot;i >> internal:role=img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>964e3242-da82-49d6-acbb-5dd33db44a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/555-bathanghai.jpg</value>
      <webElementGuid>08d952cd-cb43-45ec-bdfe-ef4e62d001ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>44e354a9-0a97-46e1-a4ee-743a72f70d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44d3e14e-fb8f-4850-9318-d75d0a523175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>708ea410-5338-4af6-8515-1fe30ab385fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block_input_chinhanh&quot;)/div[@class=&quot;list_chinhanh flexslider width_common space_bottom_10&quot;]/div[@class=&quot;flex-viewport&quot;]/ul[@class=&quot;slides&quot;]/li[2]/div[@class=&quot;item_chinhanh&quot;]/div[@class=&quot;thumb_chinhanh&quot;]/img[@class=&quot;loaded&quot;]</value>
      <webElementGuid>7b1137b5-72d3-4a84-89d7-7f47c1581968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_chinhanh']/div[2]/div[2]/ul/li[2]/div/div/img</value>
      <webElementGuid>0cadd206-526e-44ed-a2e1-d830eac5f168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/img</value>
      <webElementGuid>7a1ab05c-8495-4026-bb04-01cfb15112d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/555-bathanghai.jpg']</value>
      <webElementGuid>7891804e-54e0-4950-b171-50f0ecb3bba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
