<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__service_note</name>
   <tag></tag>
   <elementGuidId>c1e54854-87d1-4079-a8e1-599a38a21c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service_note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='service_note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập tên dịch vụ bạn muốn làm...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74692ec0-b580-4226-bfc5-fef7e4348894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>773d4662-6d0b-415a-a262-c5cfe42dc6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>7b31283c-7f1f-4ff5-b61c-02ca4dfcd30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service_note</value>
      <webElementGuid>ed37a1ba-eccd-46dd-9912-e11fa536206f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_note</value>
      <webElementGuid>3fb33152-28d2-489e-b0b2-79e416637200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên dịch vụ bạn muốn làm...</value>
      <webElementGuid>7fcec136-335e-4dff-8dca-e319ee37cc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2a02a22e-a2c3-43c0-bca1-9261eda875d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service_note&quot;)</value>
      <webElementGuid>521ba057-ea68-4818-9c93-169b73ebfb7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='service_note']</value>
      <webElementGuid>9a06bbdf-2b27-43ac-9bc4-9a9535ec7f4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_service']/div/div[2]/input[3]</value>
      <webElementGuid>a1a05f1c-9501-47e1-81a2-41d16ad7a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>321dc02f-fb42-4991-bfb8-47c33766f400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'service_note' and @name = 'service_note' and @placeholder = 'Nhập tên dịch vụ bạn muốn làm...']</value>
      <webElementGuid>af923be4-287f-44bb-9b11-6019f2a057c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
