<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__service_note</name>
   <tag></tag>
   <elementGuidId>c1e54854-87d1-4079-a8e1-599a38a21c56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#service_note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='service_note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Nhập tên dịch vụ bạn muốn làm...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54067e0b-0c8e-4a28-afd1-fbba831cd0f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a5eac45-a4f1-46d1-958b-7d5b38820927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2ced4a1f-140e-4c96-819a-31913a8e7fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>service_note</value>
      <webElementGuid>3d4d3098-05f0-4105-9225-e118bb6c2bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>service_note</value>
      <webElementGuid>fcd1a3d2-8ad8-4525-9c5a-79432677a5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tên dịch vụ bạn muốn làm...</value>
      <webElementGuid>61918a1b-a432-4e21-940d-3254fbbdb91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>fc146f30-581a-473d-987f-3cff1111fa4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;service_note&quot;)</value>
      <webElementGuid>dde6fed7-56bb-40ca-87d7-d4295067fcc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='service_note']</value>
      <webElementGuid>65711fbc-7ffd-40dd-9c7a-d0e200959175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block_input_service']/div/div[2]/input[3]</value>
      <webElementGuid>90b57cb4-98a1-4f15-8666-ede54c96925a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>b30fa423-4a06-44f2-84fb-8deae398ac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'service_note' and @name = 'service_note' and @placeholder = 'Nhập tên dịch vụ bạn muốn làm...']</value>
      <webElementGuid>81b57fc1-c4a7-45e2-b1e0-1699afa20638</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
