<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_ng nhp vi</name>
   <tag></tag>
   <elementGuidId>efb04f8e-cae0-4e06-97ea-a7441e43966c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='radix-:R1aidtshla:']/section/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Đăng nhập với&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bbf87d95-b311-47cf-856a-06c3563829ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[13px]</value>
      <webElementGuid>b6df1456-ed7d-4c5b-89f5-43c142f0b99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập với</value>
      <webElementGuid>8cff818a-4247-40da-b54b-952bd34134e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R1aidtshla:&quot;)/section[@class=&quot;flex flex-col gap-2.5 border-border py-5&quot;]/div[@class=&quot;border-b-[1px] pb-5 border-border&quot;]/p[@class=&quot;text-[13px]&quot;]</value>
      <webElementGuid>836c9c21-e28c-4150-b5f7-d3755941f6e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:R1aidtshla:']/section/div/p</value>
      <webElementGuid>2fe74752-b477-4f14-8108-85f0e243618b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vitamin / Khoáng Chất'])[1]/following::p[1]</value>
      <webElementGuid>b56d0eb0-b609-42f3-90af-1e6559f9f8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hỗ Trợ Giảm Cân'])[1]/following::p[1]</value>
      <webElementGuid>159b776a-24a4-4c66-a75b-d0d43d2d3fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhớ mật khẩu'])[1]/preceding::p[2]</value>
      <webElementGuid>7e43899a-75e5-40ea-8997-6af5ab8ba12f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[2]/preceding::p[3]</value>
      <webElementGuid>3fad5131-63c9-4c17-8179-48d3f8201127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đăng nhập với']/parent::*</value>
      <webElementGuid>a5929d0e-f709-4ab0-92ba-dab827b1261c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/section/div/p</value>
      <webElementGuid>504f303f-119b-4f8a-a8fb-d9c868e9f353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Đăng nhập với' or . = 'Đăng nhập với')]</value>
      <webElementGuid>fca747f9-901a-490e-859a-6e46fa75cf4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
