<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>82477578-cbb7-4d74-b4d2-0ba23a31e515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Icon'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Cart Nav&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2c2cdea5-a667-4cc0-bb1e-cd2bd176aaf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>fb94fe2c-b91f-42f0-a089-84378c20fe77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>fcc19ddb-8aff-4b05-989c-0b4a84fe4f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 30 30</value>
      <webElementGuid>ff9df9df-5b7e-4ad4-8807-873ad077302c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>4814905d-b9b0-4c50-9e03-93c074f74881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>dea5f740-96af-41dd-9b78-d9a42640cc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-header&quot;)/section[@class=&quot;bg-primary pb-4&quot;]/div[@class=&quot;max-w-[1400px] m-auto container flex items-center&quot;]/nav[@class=&quot;relative z-10 flex max-w-max flex-1 items-center justify-center&quot;]/div[1]/ul[@class=&quot;group flex-1 list-none justify-center space-x-1 flex items-center gap-[25px] w-full text-white&quot;]/li[@class=&quot;flex items-center&quot;]/button[@class=&quot;p-0&quot;]/a[@class=&quot;group inline-flex h-9 w-max items-center justify-center rounded-md bg-transparent text-sm font-medium transition-colors disabled:pointer-events-none disabled:opacity-50 relative hover:bg-transparent hover:text-white focus:bg-transparent focus:text-white focus:outline-none data-[active]:bg-transparent data-[state=open]:bg-transparent&quot;]/svg[1]</value>
      <webElementGuid>241a48a7-29fb-4230-b72d-5aaa3468dbe6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone Icon'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>cdb4a3ad-a5b2-430c-9aa9-b7b5cb0161d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Icon'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>71d5c110-ebee-4ab7-95de-faf0d3f60103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hamburger icon'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>1f2d39cd-36e0-40d8-8f57-20e593359a8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
