<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_H trkhch hng_loading</name>
   <tag></tag>
   <elementGuidId>acb3b8d5-8d2c-44bd-b47b-739ecd2c25a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.icon_header.relative > div > img.loading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#v3_header >> internal:role=link[name=&quot;1&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>238193fc-40b2-4d61-9b6f-d8caebd6e343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://media.hcdn.vn/hsk/icon/icon_header__cart.png</value>
      <webElementGuid>8c7022fa-b7fd-4337-8ff7-efbf2515c705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loading</value>
      <webElementGuid>d0fdbfaf-0e0b-4582-a283-fb9ae46eb554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-was-processed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>282f8a3e-3377-4b9d-929d-8de97c4bf572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;v3_header&quot;)/div[@class=&quot;container relative&quot;]/div[@class=&quot;v4_inf_right_header&quot;]/div[@class=&quot;item_header item_header_giohang minicart-wrapper&quot;]/a[@class=&quot;icon_header relative&quot;]/div[1]/img[@class=&quot;loading&quot;]</value>
      <webElementGuid>cb949678-8854-4ddb-9b02-697ebf79be24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='v3_header']/div[2]/div[3]/div[5]/a/div/img</value>
      <webElementGuid>b042a970-9489-4692-9df3-6588d97078b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://media.hcdn.vn/hsk/icon/icon_header__cart.png')]</value>
      <webElementGuid>98af5d6c-9c85-4ca4-a6ef-f6f43664f99b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/img</value>
      <webElementGuid>8d78f0fd-9fb2-45aa-9971-858d96a82031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://media.hcdn.vn/hsk/icon/icon_header__cart.png']</value>
      <webElementGuid>00a7b0c9-e50f-4b65-8c00-f4c6fbb17940</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
