<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Vui lng nhp mt khu c  di t 6 n 32 k t</name>
   <tag></tag>
   <elementGuidId>d9a368a4-efa1-454d-9705-c1802ab15ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='passwordNew-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passwordNew-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Vui lòng nhập mật khẩu có độ dài từ 6 đến 32 kí tự&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8d836848-81e2-49cd-885c-5dff64ca2d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordNew-error</value>
      <webElementGuid>ef3efff2-7453-44d3-81a0-c5bc422d032b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>help-block</value>
      <webElementGuid>8929086c-eac6-4984-89e2-fbf9c1e56141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vui lòng nhập mật khẩu có độ dài từ 6 đến 32 kí tự</value>
      <webElementGuid>f9cb841a-81ec-4a8f-b777-27d8d334a2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordNew-error&quot;)</value>
      <webElementGuid>b9fd2df1-d3b7-43a2-ae0b-58a48d23a722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='passwordNew-error']</value>
      <webElementGuid>e6ba0370-7bee-40bd-ba91-19b82bcbe748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account']/div[2]/div/div[2]/span</value>
      <webElementGuid>7f68f65c-c755-4df5-af10-7d4c74ee4381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu mới:'])[1]/following::span[1]</value>
      <webElementGuid>5d8911ba-7f47-4cb9-a817-3b8b16eea416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật khẩu hiện tại:'])[1]/following::span[1]</value>
      <webElementGuid>503420f6-74cc-4dae-997f-333dc4e8310f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhập lại:'])[1]/preceding::span[1]</value>
      <webElementGuid>0291206b-1476-437a-a5a7-cba38e24c5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cập nhật'])[1]/preceding::span[1]</value>
      <webElementGuid>bb44ba35-ffa8-4179-b193-cc574af13975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vui lòng nhập mật khẩu có độ dài từ 6 đến 32 kí tự']/parent::*</value>
      <webElementGuid>c5c927d5-f700-482a-aa5b-77d9584bd5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>4519af1b-a808-4d5d-af10-ff4b697c3d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'passwordNew-error' and (text() = 'Vui lòng nhập mật khẩu có độ dài từ 6 đến 32 kí tự' or . = 'Vui lòng nhập mật khẩu có độ dài từ 6 đến 32 kí tự')]</value>
      <webElementGuid>6c85b22c-e954-4610-9974-c00e920d2d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
